services:
  fluent-bit:
    build: ./fluentbit
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:9.1.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
