name: Deploy
on:
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fluentbit
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Build docker image
        run: docker build --tag $DOCKER_IMAGE .
      - name: Push to container registry
        run: docker push $DOCKER_IMAGE
  run-apibox:
    needs: deploy
    runs-on: ubuntu-latest
    env:
      NAME: server-logging
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APIBOX_URL }}
          username: ${{ secrets.APIBOX_USER }}
          key: ${{ secrets.APIBOX_SSH_KEY }}
          port: ${{ secrets.APIBOX_PORT }}
          envs: NAME,DOCKER_IMAGE
          script_stop: true
          script: |
            docker pull ${DOCKER_IMAGE}
            docker stop ${NAME} && docker rm ${NAME} || true
            docker run \
                --name ${NAME} \
                --detach \
                --restart on-failure \
                --volume /var/lib/docker/containers:/var/lib/docker/containers:ro \
                ${DOCKER_IMAGE}
  # run-certbox:
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   env:
  #     NAME: server-logging
  #     DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
  #   steps:
  #     - name: executing remote ssh commands
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.CERTBOX_URL }}
  #         username: ${{ secrets.CERTBOX_USER }}
  #         key: ${{ secrets.CERTBOX_SSH_KEY }}
  #         port: ${{ secrets.CERTBOX_PORT }}
  #         envs: NAME,DOCKER_IMAGE
  #         script_stop: true
  #         script: |
  #           docker pull ${DOCKER_IMAGE}
  #           docker stop ${NAME} && docker rm ${NAME} || true
  #           docker run \
  #               --name ${NAME} \
  #               --detach \
  #               --restart on-failure \
  #               ${DOCKER_IMAGE}
  # run-workerbox:
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   env:
  #     NAME: server-logging
  #     DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
  #   steps:
  #     - name: executing remote ssh commands
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.WORKERBOX_URL }}
  #         username: ${{ secrets.WORKERBOX_USER }}
  #         key: ${{ secrets.WORKERBOX_SSH_KEY }}
  #         port: ${{ secrets.WORKERBOX_PORT }}
  #         envs: NAME,DOCKER_IMAGE
  #         script_stop: true
  #         script: |
  #           docker pull ${DOCKER_IMAGE}
  #           docker stop ${NAME} && docker rm ${NAME} || true
  #           docker run \
  #               --name ${NAME} \
  #               --detach \
  #               --restart on-failure \
  #               ${DOCKER_IMAGE}
  # run-mdtpbox:
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   env:
  #     NAME: server-logging
  #     DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
  #   steps:
  #     - name: executing remote ssh commands
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.MDTPBOX_URL }}
  #         username: ${{ secrets.MDTPBOX_USER }}
  #         key: ${{ secrets.MDTPBOX_SSH_KEY }}
  #         port: ${{ secrets.MDTPBOX_PORT }}
  #         envs: NAME,DOCKER_IMAGE
  #         script_stop: true
  #         script: |
  #           docker pull ${DOCKER_IMAGE}
  #           docker stop ${NAME} && docker rm ${NAME} || true
  #           docker run \
  #               --name ${NAME} \
  #               --detach \
  #               --restart on-failure \
  #               ${DOCKER_IMAGE}
